config/routes.rb
Teisotcl::Application.routes.draw do
  root :to => 'home#index'
  resources :participants do
    collection do
      get :dashboard, :edit_password, :invitation
      post :update_password
    end
    member do
      get :edit_thesis, :show_thesis
    end
  end
  resources :experts do
    collection do
      get :dashboard, :edit_password
      post :update_password
    end
    resources :ratings do
      collection do
        get :unrate, :rated, :standard
      end
    end
  end
  resources :articles
  resources :bookings
  match 'intro' => 'intro#index', :as => :intro
  match 'participant_signup' => 'participants#new', :as => :participant_signup, :via => [:get]
  match 'participant_signup' => 'participants#create', :as => :participant_signup, :via => [:post]
  match 'participant_signin' => 'sessions#new_participant', :as => :participant_signin, :via => [:get]
  match 'participant_signin' => 'sessions#create_participant', :as => :participant_signin, :via => [:post]
  match 'participant_signout' => 'sessions#destroy_participant', :as => :participant_signout
  match 'expert_signin' => 'sessions#new_expert', :as => :expert_signin, :via => [:get]
  match 'expert_signin' => 'sessions#create_expert', :as => :expert_signin, :via => [:post]
  match 'expert_signout' => 'sessions#destroy_expert', :as => :expert_signout
  namespace :admin do
    root :to => 'dashboard#index'
    resources :participants do
      member do
        get :reset_password, :simulate_signin, :register, :pay_fee, :pay_isclt_fee, :attend_banquet, :attend_congress, :tour_museum, :tour_tw
      end
      collection do
        get :search, :approved, :registered, :unregister
      end
      resource :thesis do
        resources :ratings
      end
    end
    resources :theses do
      collection do
        get :rated, :unrate, :submited, :search, :archive
      end
    end
    resources :experts do
      member do
        get :reset_password, :simulate_signin
      end
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :articles
    resources :posters
    resources :users do
      member do
        get :reset_password
      end
    end
    resources :reviews
    resources :ratings do
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :hotels do
      resources :rooms
    end
    resources :excels do
      collection do
        get :export_thesis_author_participants, :export_nonvoting_participants, :export_approved_participants, :export_submited_participants, :export_participants_with_registration, :export_experts, :export_reviews, :export_bookings
      end
    end
    resource :election
    match 'excels' => 'excels', :as => :excels
    match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
    match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
    match 'signout' => 'sessions#destroy', :as => :signout
    match 'edit_password' => 'users#edit_password', :as => :edit_password
    match 'update_password' => 'users#update_password', :as => :update_password, :via => [:post]
  end

end

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>第十一届国际汉语教学研讨会管理系统</title>
    <%= stylesheet_link_tag "meta", "admin", "jquery-ui", :media => "all" %>
    <%= javascript_include_tag "application", "/ckeditor/ckeditor.js" %>
    <%= yield :head %>
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0"> 
  </head>
  <body>
    <div id="header">
      <div class="container">
        <span>第十一届国际汉语教学研讨会管理系统</span>
        <div id="pi">
          <ul>
            <li>
              <%= image_tag 'admin/portrait.gif' %>
              欢迎您，<%= session[:user_name] %> | <%= link_to '修改密码', admin_edit_password_path %> | <%= link_to '注销', admin_signout_path %>
            </li>
            <li class="date">上次登录时间：<%= human_datetime_tag session[:user_last_signined_at] %></li>
          </ul>
        </div>
        <div class="cb"></div>
      </div>
    </div>
    <div id="navi">
      <div class="container">
        <ul>
          <li><%= link_to '控制面板', admin_root_path %></li>
          <li><a href="#">签到管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '已签到代表', registered_admin_participants_path %></li>
              <li><%= link_to '未签到代表', unregister_admin_participants_path %></li>
            </ul>
          </li>
          <% if session[:user_role] != User::RoleVolunteer %>
          <li><a href="#">参会者管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '参会者列表', approved_admin_participants_path %></li>
              <li><%= link_to '添加参会者', new_admin_participant_path %></li>
              <li><%= link_to '已提交代表', submited_admin_theses_path %></li>
            </ul>
          </li>
          <!--li><a href="#">专家管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '专家列表', admin_experts_path %></li>
              <li><%= link_to '添加专家', new_admin_expert_path %></li>
              <li><%= link_to '批量添加', batched_new_admin_experts_path %></li>
            </ul>
          </li>
          <li><a href="#">评审管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '评审列表', admin_reviews_path %></li>
              <li><%= link_to '添加评审', new_admin_review_path %></li>
              <li><%= link_to '批量指派', batched_new_admin_ratings_path %></li>
            </ul>
          </li-->
          <li><a href="#">内容管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '文章列表', admin_articles_path %></li>
              <li><%= link_to '添加文章', new_admin_article_path %></li>
              <li><%= link_to '海报管理', admin_posters_path %></li>
              <li><%= link_to '添加海报', new_admin_poster_path %></li>
            </ul>
          </li>
          <li><a href="#">酒店管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '酒店列表', admin_hotels_path %></li>
              <li><%= link_to '添加酒店', new_admin_hotel_path %></li>
            </ul>
          </li>
          <% if session[:user_role] == User::RoleAdmin %>
          <li><a href="#">系统管理<%= image_tag 'admin/navi_arrow.gif' %></a>
            <ul>
              <li><%= link_to '用户列表', admin_users_path %></li>
              <li><%= link_to '添加用户', new_admin_user_path %></li>
              <li><%= link_to '选举模拟', new_admin_election_path %></li>
            </ul>
          </li>
          <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div id="content">
      <div class="container">
        <%= yield %>
        <div class="cb"></div>
      </div>
    </div>
    <div id="footer">
      <div class="container">
        <span>Copyright 世界汉语教学学会 @2012</span>
      </div>
    </div>
  </body>
</html>