config/routes.rb
Teisotcl::Application.routes.draw do
  root :to => 'home#index'
  resources :participants do
    collection do
      get :dashboard, :edit_password, :invitation
      post :update_password
    end
    member do
      get :edit_thesis, :show_thesis
    end
  end
  resources :experts do
    collection do
      get :dashboard, :edit_password
      post :update_password
    end
    resources :ratings do
      collection do
        get :unrate, :rated, :standard
      end
    end
  end
  resources :articles
  resources :bookings
  match 'intro' => 'intro#index', :as => :intro
  match 'participant_signup' => 'participants#new', :as => :participant_signup, :via => [:get]
  match 'participant_signup' => 'participants#create', :as => :participant_signup, :via => [:post]
  match 'participant_signin' => 'sessions#new_participant', :as => :participant_signin, :via => [:get]
  match 'participant_signin' => 'sessions#create_participant', :as => :participant_signin, :via => [:post]
  match 'participant_signout' => 'sessions#destroy_participant', :as => :participant_signout
  match 'expert_signin' => 'sessions#new_expert', :as => :expert_signin, :via => [:get]
  match 'expert_signin' => 'sessions#create_expert', :as => :expert_signin, :via => [:post]
  match 'expert_signout' => 'sessions#destroy_expert', :as => :expert_signout
  namespace :admin do
    root :to => 'dashboard#index'
    resources :participants do
      member do
        get :reset_password, :simulate_signin, :register, :pay_fee, :pay_isclt_fee, :attend_banquet, :attend_congress, :tour_museum, :tour_tw
      end
      collection do
        get :search, :approved, :registered, :unregister
      end
      resource :thesis do
        resources :ratings
      end
    end
    resources :theses do
      collection do
        get :rated, :unrate, :submited, :search, :archive
      end
    end
    resources :experts do
      member do
        get :reset_password, :simulate_signin
      end
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :articles
    resources :posters
    resources :users do
      member do
        get :reset_password
      end
    end
    resources :reviews
    resources :ratings do
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :hotels do
      resources :rooms
    end
    resources :excels do
      collection do
        get :export_thesis_author_participants, :export_nonvoting_participants, :export_approved_participants, :export_submited_participants, :export_participants_with_registration, :export_experts, :export_reviews, :export_bookings
      end
    end
    resource :election
    match 'excels' => 'excels', :as => :excels
    match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
    match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
    match 'signout' => 'sessions#destroy', :as => :signout
    match 'edit_password' => 'users#edit_password', :as => :edit_password
    match 'update_password' => 'users#update_password', :as => :update_password, :via => [:post]
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_attached_file :image, :path => ":rails_root/public/assets/hotels/:hash.:extension", :url => "/assets/hotels/:hash.:extension", :hash_secret => "CGmWFauN1P4tIe3kiDjFDusghm2LX"
  has_many :rooms
end

app/controllers/admin/hotels_controller.rb
# -*- encoding : utf-8 -*-
class Admin::HotelsController < Admin::BaseController
  
  def index
    @hotels = Hotel.paginate :page => params[:page]
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def create
    @hotel = Hotel.new(params[:hotel])
    if @hotel.save
      redirect_to [:admin, @hotel], notice: '创建成功'
    else
      render action: 'new'
    end
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update_attributes(params[:hotel])
      redirect_to [:admin, @hotel], notice: '更新成功'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    redirect_to admin_hotels_url, notice: '删除成功'
  end
end

app/views/admin/hotels/edit.html.erb
<div id="notice">
  <h1>编辑酒店</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= form_for [:admin, @hotel], :html => { :multipart => true } do |f| %>
      <%= render "admin/shared/error_messages", :target => @hotel %>
      <fieldset class="form-generic">
        <legend>酒店信息</legend>
        <ul>
          <li>
            <label>名称：</label><%= f.text_field :name, :class => 'text-field' %>
          </li>
          <li>
            <label>地址：</label><%= f.text_field :address, :class => 'text-field' %>
          </li>
          <li>
            <label>电话：</label><%= f.text_field :phone, :class => 'text-field' %>
          </li>
          <li>
            <label>网址：</label><%= f.text_field :website, :class => 'text-field' %>
          </li>
          <li>
            <label>图片：</label><%= f.file_field :image, :class => 'file-field' %>
          </li>
          <li>
            <label>简介：</label><%= f.text_area :description, :class => 'text-area' %>
          </li>
        </ul>
      </fieldset>
      <div class="action-generic">
        <%= link_to '修改', '#', :onclick => "submitForm('edit_hotel_#{@hotel.id}')", :class => 'button' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/hotels/index.html.erb
<div id="notice">
  <h1>酒店列表</h1>
</div>
<div id="side">
  <div class="portlet">
    <div class="title">相关功能</div>
    <div class="content">
      <ul>
        <li><%= link_to '导出预订信息Excel', export_bookings_admin_excels_path(:format => :xls) %></li>
      </ul>
    </div>
  </div>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>名称</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @hotels.each do |hotel| %>
            <tr>
              <td><%= link_to hotel.name, [:admin, hotel] %></td>
              <td><%= edit_tag hotel %> <%= destroy_tag hotel %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @hotels %>
    </div>
  </div>
</div>

app/views/admin/hotels/new.html.erb
<div id="notice">
  <h1>添加酒店</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= form_for [:admin, @hotel], :html => { :multipart => true } do |f| %>
      <%= render "admin/shared/error_messages", :target => @hotel %>
      <fieldset class="form-generic">
        <legend>酒店信息</legend>
        <ul>
          <li>
            <label>名称：</label><%= f.text_field :name, :class => 'text-field' %>
          </li>
          <li>
            <label>地址：</label><%= f.text_field :address, :class => 'text-field' %>
          </li>
          <li>
            <label>电话：</label><%= f.text_field :phone, :class => 'text-field' %>
          </li>
          <li>
            <label>网址：</label><%= f.text_field :website, :class => 'text-field' %>
          </li>
          <li>
            <label>图片：</label><%= f.file_field :image, :class => 'file-field' %>
          </li>
          <li>
            <label>简介：</label><%= f.text_area :description, :class => 'text-area' %>
          </li>
        </ul>
      </fieldset>
      <div class="action-generic">
        <%= link_to '添加', '#', :onclick => "submitForm('new_hotel')", :class => 'button' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/hotels/show.html.erb
<div id="notice">
  <h1>查看酒店</h1>
</div>
<div id="side">
  <div class="portlet">
    <div class="title">相关功能</div>
    <div class="content">
      <ul>
        <li><%= link_to '添加房型', new_admin_hotel_room_path(@hotel) %></li>
      </ul>
    </div>
  </div>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <fieldset class="form-generic">
        <legend>酒店信息</legend>
        <ul>
          <li>
            <label>名称：</label><%= @hotel.name %>
          </li>
          <li>
            <label>地址：</label><%= @hotel.address %>
          </li>
          <li>
            <label>电话：</label><%= @hotel.phone %>
          </li>
          <li>
            <label>网址：</label><%= @hotel.website %>
          </li>
          <li>
            <label>图片：</label><%= link_to image_tag(@hotel.image.url), @hotel.image.url, :target => '_blank' %>
          </li>
          <li>
            <label>简介：</label><%= @hotel.description %>
          </li>
        </ul>
      </fieldset>
      <fieldset class="form-generic">
        <legend>房型信息</legend>
        <ul>
          <% @hotel.rooms.each do |room| %>
          <li>
            <label><%= room.name %>：</label>共<%= room.quota %>间，<%= room.quota * room.bed_amount %>个床位，原价<%= room.price %>元/间，参会价<%= room.discount_price %>元/间
            <%= link_to '[修改]', edit_admin_hotel_room_path(@hotel, room) %>
            <%= link_to '[删除]', admin_hotel_room_path(@hotel, room), confirm: '确定要删除吗？', method: :delete %>
          </li>
          <% end %>
        </ul>
      </fieldset>
      <div class="action-generic">
        <%= link_to '编辑', edit_admin_hotel_path(@hotel), :class => 'button' %>
        <%= link_to '删除', [:admin, @hotel], confirm: '确定要删除吗？', :method => :delete, :class => 'button' %>
        <%= link_to '返回列表', admin_hotels_path, :class => 'button' %>
      </div>
    </div>
  </div>
</div>