config/routes.rb
Teisotcl::Application.routes.draw do
  root :to => 'home#index'
  resources :participants do
    collection do
      get :dashboard, :edit_password, :invitation
      post :update_password
    end
    member do
      get :edit_thesis, :show_thesis
    end
  end
  resources :experts do
    collection do
      get :dashboard, :edit_password
      post :update_password
    end
    resources :ratings do
      collection do
        get :unrate, :rated, :standard
      end
    end
  end
  resources :articles
  resources :bookings
  match 'intro' => 'intro#index', :as => :intro
  match 'participant_signup' => 'participants#new', :as => :participant_signup, :via => [:get]
  match 'participant_signup' => 'participants#create', :as => :participant_signup, :via => [:post]
  match 'participant_signin' => 'sessions#new_participant', :as => :participant_signin, :via => [:get]
  match 'participant_signin' => 'sessions#create_participant', :as => :participant_signin, :via => [:post]
  match 'participant_signout' => 'sessions#destroy_participant', :as => :participant_signout
  match 'expert_signin' => 'sessions#new_expert', :as => :expert_signin, :via => [:get]
  match 'expert_signin' => 'sessions#create_expert', :as => :expert_signin, :via => [:post]
  match 'expert_signout' => 'sessions#destroy_expert', :as => :expert_signout
  namespace :admin do
    root :to => 'dashboard#index'
    resources :participants do
      member do
        get :reset_password, :simulate_signin, :register, :pay_fee, :pay_isclt_fee, :attend_banquet, :attend_congress, :tour_museum, :tour_tw
      end
      collection do
        get :search, :approved, :registered, :unregister
      end
      resource :thesis do
        resources :ratings
      end
    end
    resources :theses do
      collection do
        get :rated, :unrate, :submited, :search, :archive
      end
    end
    resources :experts do
      member do
        get :reset_password, :simulate_signin
      end
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :articles
    resources :posters
    resources :users do
      member do
        get :reset_password
      end
    end
    resources :reviews
    resources :ratings do
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :hotels do
      resources :rooms
    end
    resources :excels do
      collection do
        get :export_thesis_author_participants, :export_nonvoting_participants, :export_approved_participants, :export_submited_participants, :export_participants_with_registration, :export_experts, :export_reviews, :export_bookings
      end
    end
    resource :election
    match 'excels' => 'excels', :as => :excels
    match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
    match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
    match 'signout' => 'sessions#destroy', :as => :signout
    match 'edit_password' => 'users#edit_password', :as => :edit_password
    match 'update_password' => 'users#update_password', :as => :update_password, :via => [:post]
  end

end

app/controllers/admin/theses_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ThesesController < Admin::BaseController
  
  def index
    @theses = Thesis.order('created_at DESC').paginate :page => params[:page]
  end
  
  def rated
    @theses = Thesis.rated.paginate :page => params[:page]
  end
  
  def unrate
    @theses = Thesis.unrate.paginate :page => params[:page]
  end
  
  def submited
    @theses = Thesis.submited.approved.order('document_updated_at DESC').paginate :page => params[:page]
  end
  
  def search
    @keyword = params[:keyword].strip
    if @keyword.blank?
      redirect_to admin_theses_path
    else
      @theses = Thesis.search(params[:keyword]).paginate :page => params[:page]
      render 'result'
    end
  end
  
  def archive
    archive_name = Thesis.archive
    send_file "#{::Rails.root.to_s}/public/archives/#{archive_name}", :filename => archive_name, :type => 'application/octet-stream'
  end
end

app/views/admin/theses/index.html.erb
<div id="notice">
  <h1>论文列表</h1>
</div>
<div id="side">
  <div class="portlet">
    <div class="title">相关功能</div>
    <div class="content">
      <div class="search-generic">
        <%= form_tag search_admin_theses_path, :id => 'search_theses', :method => :get do %>
          <%= text_field_tag :keyword, nil, :class => 'text-field' %>
          <%= link_to '搜索', '#', :onclick => "submitForm('search_theses')", :class => 'button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>论文题目</td>
            <td>第一作者</td>
            <td>综合评审信息</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @theses.each do |thesis| %>
            <tr>
              <td>
                <%= link_to thesis.subject.truncate(30), [:admin, thesis.participant], :id => "thesis-#{thesis.id}" %>
                <%= javascript_tag do %>
                  $("a#thesis-<%= thesis.id %>").qtip({
                    content: "<%= thesis.subject %>",
                    style: {
                      name: 'light',
                      tip: 'topLeft'
                    }
                  });
                <% end %>
              </td>
              <td><%= thesis.first_author.truncate(4) %></td>
              <td><%= raw human_general_rating_tag thesis %></td>
              <td><%= edit_tag thesis.participant %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @theses %>
    </div>
  </div>
</div>

app/views/admin/theses/rated.html.erb
<div id="notice">
  <h1>已评审论文列表</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title">共<%= @theses.count %>篇</div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>论文题目</td>
            <td>第一作者</td>
            <td>评审信息</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @theses.each do |thesis| %>
            <tr>
              <td>
                <%= link_to thesis.subject.truncate(20), [:admin, thesis.participant], :id => "thesis-#{thesis.id}" %>
                <%= javascript_tag do %>
                  $("a#thesis-<%= thesis.id %>").qtip({
                    content: "<%= thesis.subject %>",
                    style: {
                      name: 'light',
                      tip: 'topLeft'
                    }
                  });
                <% end %>
              </td>
              <td><%= thesis.first_author.truncate(4) %></td>
              <td><%= raw human_rating_for_list_tag thesis.ratings %></td>
              <td><%= edit_tag thesis.participant %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @thesesasdfasdf %>
    </div>
  </div>
</div>

app/views/admin/theses/result.html.erb
<div id="notice">
  <h1>“<%= @keyword %>”的搜索结果</h1>
</div>
<div id="side">
  <div class="portlet">
    <div class="title">相关功能</div>
    <div class="content">
      <div class="search-generic">
        <%= form_tag search_admin_theses_path, :id => 'search_theses', :method => :get do %>
          <%= text_field_tag :keyword, nil, :class => 'text-field' %>
          <%= link_to '搜索', '#', :onclick => "submitForm('search_theses')", :class => 'button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>论文题目</td>
            <td>第一作者</td>
            <td>综合评审信息</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @theses.each do |thesis| %>
            <tr>
              <td>
                <%= link_to thesis.subject.truncate(30), [:admin, thesis.participant], :id => "thesis-#{thesis.id}" %>
                <%= javascript_tag do %>
                  $("a#thesis-<%= thesis.id %>").qtip({
                    content: "<%= thesis.subject %>",
                    style: {
                      name: 'light',
                      tip: 'topLeft'
                    }
                  });
                <% end %>
              </td>
              <td><%= thesis.first_author.truncate(4) %></td>
              <td><%= raw human_general_rating_tag thesis %></td>
              <td><%= edit_tag thesis.participant %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @theses %>
    </div>
  </div>
</div>

app/views/admin/theses/submited.html.erb
<div id="notice">
  <h1>已提交论文列表</h1>
</div>
<div id="side">
  <div class="portlet">
    <div class="title">相关功能</div>
    <div class="content">
      <ul>
        <li><%= link_to '批量下载RAR',archive_admin_theses_path %></li>
      </ul>
    </div>
  </div>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>论文题目</td>
            <td>全文评审信息</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @theses.each do |thesis| %>
            <tr>
              <td>
                <%= link_to thesis.subject.truncate(25), [:admin, thesis.participant], :id => "thesis-#{thesis.id}" %>
                <%= javascript_tag do %>
                  $("a#thesis-<%= thesis.id %>").qtip({
                    content: "<%= thesis.subject %>",
                    style: {
                      name: 'light',
                      tip: 'topLeft'
                    }
                  });
                <% end %>
              </td>
              <td><%= human_rating_for_list_tag thesis.ratings.for_review(Review.find(2)) %></td>
              <td><%= edit_tag thesis.participant %> <%= link_to raw("#{image_tag 'admin/disk.gif'} 下载论文"), thesis.document_url, :target => '_blank' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @theses %>
    </div>
  </div>
</div>

app/views/admin/theses/unrate.html.erb
<div id="notice">
  <h1>未评审论文列表</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title">共<%= @theses.count.count %>篇</div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>论文题目</td>
            <td>第一作者</td>
            <td>关键词</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @theses.each do |thesis| %>
            <tr>
              <td>
                <%= link_to thesis.subject.truncate(20), [:admin, thesis.participant], :id => "thesis-#{thesis.id}" %>
                <%= javascript_tag do %>
                  $("a#thesis-<%= thesis.id %>").qtip({
                    content: "<%= thesis.subject %>",
                    style: {
                      name: 'light',
                      tip: 'topLeft'
                    }
                  });
                <% end %>
              </td>
              <td><%= thesis.first_author.truncate(4) %></td>
              <td><%= thesis.keywords.truncate(12) %></td>
              <td><%= edit_tag thesis.participant %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @theses %>
    </div>
  </div>
</div>