config/routes.rb
Teisotcl::Application.routes.draw do
  root :to => 'home#index'
  resources :participants do
    collection do
      get :dashboard, :edit_password, :invitation
      post :update_password
    end
    member do
      get :edit_thesis, :show_thesis
    end
  end
  resources :experts do
    collection do
      get :dashboard, :edit_password
      post :update_password
    end
    resources :ratings do
      collection do
        get :unrate, :rated, :standard
      end
    end
  end
  resources :articles
  resources :bookings
  match 'intro' => 'intro#index', :as => :intro
  match 'participant_signup' => 'participants#new', :as => :participant_signup, :via => [:get]
  match 'participant_signup' => 'participants#create', :as => :participant_signup, :via => [:post]
  match 'participant_signin' => 'sessions#new_participant', :as => :participant_signin, :via => [:get]
  match 'participant_signin' => 'sessions#create_participant', :as => :participant_signin, :via => [:post]
  match 'participant_signout' => 'sessions#destroy_participant', :as => :participant_signout
  match 'expert_signin' => 'sessions#new_expert', :as => :expert_signin, :via => [:get]
  match 'expert_signin' => 'sessions#create_expert', :as => :expert_signin, :via => [:post]
  match 'expert_signout' => 'sessions#destroy_expert', :as => :expert_signout
  namespace :admin do
    root :to => 'dashboard#index'
    resources :participants do
      member do
        get :reset_password, :simulate_signin, :register, :pay_fee, :pay_isclt_fee, :attend_banquet, :attend_congress, :tour_museum, :tour_tw
      end
      collection do
        get :search, :approved, :registered, :unregister
      end
      resource :thesis do
        resources :ratings
      end
    end
    resources :theses do
      collection do
        get :rated, :unrate, :submited, :search, :archive
      end
    end
    resources :experts do
      member do
        get :reset_password, :simulate_signin
      end
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :articles
    resources :posters
    resources :users do
      member do
        get :reset_password
      end
    end
    resources :reviews
    resources :ratings do
      collection do
        get :batched_new
        post :batched_create
      end
    end
    resources :hotels do
      resources :rooms
    end
    resources :excels do
      collection do
        get :export_thesis_author_participants, :export_nonvoting_participants, :export_approved_participants, :export_submited_participants, :export_participants_with_registration, :export_experts, :export_reviews, :export_bookings
      end
    end
    resource :election
    match 'excels' => 'excels', :as => :excels
    match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
    match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
    match 'signout' => 'sessions#destroy', :as => :signout
    match 'edit_password' => 'users#edit_password', :as => :edit_password
    match 'update_password' => 'users#update_password', :as => :update_password, :via => [:post]
  end

end

app/models/expert.rb
# -*- encoding : utf-8 -*-
class Expert < ActiveRecord::Base
  has_secure_password
  belongs_to :thesis
  validates :password, :password_confirmation, :format => { :with => /\A[a-zA-Z0-9_]+\z/, :message => "只能使用英文、数字及下划线" }, :length => { :in => 6..16 }, :presence => true, :on => :create
  validates :name, :length => { :maximum => 100 }, :presence => true
  has_many :ratings do
    def for_review review
      where(:review_id => review.id)
    end
    
    def unrate
      includes(:thesis).where(:rated_at => nil)
    end
    
    def rated
      includes(:thesis).where('rated_at IS NOT NULL')
    end
  end
  class << self
    def available_for thesis
      where('id NOT IN (?)', Rating.where(:thesis_id => thesis.id).all.map{ |r| r.expert_id } << 0)
    end
    
    def batched_create account_and_passwords
      account_and_passwords.each do |aap|
        aap_array = aap.split(',').map{|aop| aop.strip unless aop.strip.blank?}.compact
        create({ :account => aap_array[0], :password => aap_array[1], :password_confirmation => aap_array[1], :name => aap_array[0]}) if aap_array.size == 2
      end
    end
  end
end

app/controllers/admin/experts_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ExpertsController < Admin::BaseController
  
  def index
    @experts = Expert.paginate :page => params[:page]
  end

  def show
    @reviews = Review.all
    @expert = Expert.find(params[:id])
  end

  def new
    @expert = Expert.new
  end

  def edit
    @expert = Expert.find(params[:id])
  end

  def create
    @expert = Expert.new(params[:expert])
    if @expert.save
      redirect_to [:admin, @expert], notice: '创建成功'
    else
      render action: 'new'
    end
  end
  
  def batched_create
    account_and_passwords = params[:account_and_passwords].split(/[\r\n]/).map{|aap| aap.strip unless aap.strip.blank?}.compact
    Expert.batched_create account_and_passwords
    redirect_to admin_experts_url, :notice => '批量添加成功'
  end

  def update
    @expert = Expert.find(params[:id])
    if @expert.update_attributes(params[:expert])
      redirect_to [:admin, @expert], notice: '更新成功'
    else
      render action: 'edit'
    end
  end
  
  def reset_password
    new_password = rand.to_s[-6, 6]
    @expert = Expert.find(params[:id])
    @expert.update_attributes :password => new_password, :password_confirmation => new_password
    redirect_to [:admin, @expert], notice: "密码重置成功，新密码为#{new_password}"
  end
  
  def simulate_signin
    @expert = Expert.find(params[:id])
    session[:expert_id] = @expert.id
    session[:expert_name] = @expert.name
    session[:expert_last_signined_at] = @expert.last_signined_at
    redirect_to dashboard_experts_url
  end
end

app/controllers/experts_controller.rb
# -*- encoding : utf-8 -*-
class ExpertsController < ApplicationController
  before_filter :authenticate_expert

  def dashboard
    @unrate_rating_count = Expert.find(session[:expert_id]).ratings.for_review(Review.find(2)).unrate.count
  end

  def update
    @expert = Expert.find(params[:id])
    if @expert.update_attributes(params[:expert])
      params[:edit_thesis] ? render('update_thesis_successful') : render('update_successful')
    else
      params[:edit_thesis] ? render(action: 'edit_thesis') : render(action: 'edit')
    end
  end
  
  def update_password
    @expert = Expert.find(session[:expert_id])
    if !@expert.authenticate(params[:original_password])
      flash[:alert] = '原密码输入不正确'
    elsif params[:new_password] != params[:confirmed_password]
      flash[:alert] = '两次新密码输入不一致'
    elsif params[:new_password].blank?
      flash[:alert] = '新密码不能为空'
    elsif params[:new_password] !~ /^[a-zA-Z0-9_]{6,16}$/
      flash[:alert] = '新密码只能使用英文、数字及下划线，并保持长度为6至16位'
    else
      @expert.update_attributes :password => params[:new_password], :password_confirmation => params[:new_password]
      flash[:notice] = '密码修改成功'
    end
    redirect_to edit_password_experts_url
  end
  
  protected
  def authenticate_expert_id
    unless params[:id].blank?
      params[:id] = session[:expert_id] if params[:id] != session[:expert_id]
    end
  end
  
  def authenticate_expert
    if session[:expert_id].blank?
      redirect_to expert_signin_url
    end
  end
end

app/views/admin/experts/batched_new.html.erb
<div id="notice">
  <h1>批量添加专家</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= form_tag batched_create_admin_experts_path, :id => 'batched_new_ratings' do %>
      <fieldset class="form-generic">
        <legend>专家信息</legend>
        <ul>
          <li>
            <%= text_area_tag :account_and_passwords, nil, :class => 'text-area' %><span>账号和密码用逗号分割</span>
          </li>
        </ul>
      </fieldset>
      <div class="action-generic">
        <%= link_to '批量添加', '#', :onclick => "submitForm('batched_new_ratings')", :class => 'button' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/experts/edit.html.erb
<div id="notice">
  <h1>编辑专家</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= form_for [:admin, @expert] do |f| %>
      <%= render "admin/shared/error_messages", :target => @expert %>
      <fieldset class="form-generic">
        <legend>专家信息</legend>
        <ul>
          <li>
            <label>账号：</label><%= @expert.account %>
          </li>
          <li>
            <label>姓名：</label><%= f.text_field :name, :class => 'text-field' %>
          </li>
        </ul>
      </fieldset>
      <div class="action-generic">
        <%= link_to '修改', '#', :onclick => "submitForm('edit_expert_#{@expert.id}')", :class => 'button' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/experts/index.html.erb
<div id="notice">
  <h1>专家列表</h1>
</div>
<div id="side">
  <div class="portlet">
    <div class="title">相关功能</div>
    <div class="content">
      <ul>
        <li><%= link_to '导出Excel',export_experts_admin_excels_path(:format => :xls) %></li>
      </ul>
    </div>
  </div>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <table class="list-generic">
        <thead>
          <tr>
            <td>名称</td>
            <td>评审信息</td>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <% @experts.each do |expert| %>
            <tr>
              <td><%= link_to expert.name, [:admin, expert] %></td>
              <td>已评审<%= expert.ratings.rated.count %>篇，未评审<%= expert.ratings.unrate.count %>篇</td>
              <td><%= edit_tag expert %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @experts %>
    </div>
  </div>
</div>

app/views/admin/experts/new.html.erb
<div id="notice">
  <h1>添加专家</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= form_for [:admin, @expert] do |f| %>
      <%= render "admin/shared/error_messages", :target => @expert %>
      <fieldset class="form-generic">
        <legend>专家信息</legend>
        <ul>
          <li>
            <label>账号：</label><%= f.text_field :account, :class => 'text-field' %>
          </li>
          <li>
            <label>姓名：</label><%= f.text_field :name, :class => 'text-field' %>
          </li>
          <li>
            <label>密码：</label><%= f.password_field :password, :class => 'text-field' %>
          </li>
          <li>
            <label>密码确认：</label><%= f.password_field :password_confirmation, :class => 'text-field' %>
          </li>
        </ul>
      </fieldset>
      <div class="action-generic">
        <%= link_to '添加', '#', :onclick => "submitForm('new_expert')", :class => 'button' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/experts/show.html.erb
<div id="notice">
  <h1>查看专家</h1>
</div>
<div id="side">
  <%= render "admin/shared/shortcut" %>
</div>
<div id="main">
  <div class="portlet">
    <div class="title"></div>
    <div class="content">
      <%= flash_tag %>
      <fieldset class="form-generic">
        <legend>专家信息</legend>
        <ul>
          <li>
            <label>账号：</label><%= @expert.account %>
          </li>
          <li>
            <label>名称：</label><%= @expert.name %>
          </li>
          <li>
            <label>上次登录时间：</label><%= human_datetime_tag @expert.last_signined_at %>
          </li>
        </ul>
      </fieldset>
      <% @reviews.each do |review| %>
      <fieldset class="form-generic">
        <legend><%= review.name %></legend>
        <%= expert_review_tag @expert, review %>
      </fieldset>
      <% end %>
      <div class="action-generic">
        <%= link_to '编辑', edit_admin_expert_path(@expert), :class => 'button' %>
        <%= link_to '重置密码', reset_password_admin_expert_path(@expert), :confirm => '确定要重置密码吗？', :class => 'button' %>
        <%= link_to '模拟登录', simulate_signin_admin_expert_path(@expert), :target => '_blank', :class => 'button' %>
        <%= link_to '返回列表', admin_experts_path, :class => 'button' %>
      </div>
    </div>
  </div>
</div>